### ISSUE TITLE
Example BLE.cs for Shatalmic Plugin?

### ISSUE THREAD

**Issue by djhardrich** [ParticulaCode/GoDiceUnityDemo#2]
Closed, working in iOS with the instructions in the updated Readme! Thank you!

**Comment by MarkZaytsev** [comment]
Hi. I believe everything should work just fine if you download the GoDice
Unity demo project and add Shatalmic BLE Plugin. Then you need to reference
its assembly definition and enable the define. Keep in mind that some parts
of the Shatalmic BLE Plugin should be stored in the Plugins folder.

We are going to post a video tutorial on YouTube soon. Hope this will help
you.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
