### ISSUE TITLE
Bluetooth Bridge

### ISSUE THREAD

**Issue by potter3366** [ParticulaCode/GoDiceUnityDemo#5]
Following all instructions, I get this error (Unity 2021.3.34f1)..

![error](https://github.com/ParticulaCode/GoDiceUnityDemo/assets/3511752/d4aa5aff-c901-4e7d-a59f-d3f499745ed7)

What did I do wrong? Thanks for your time!

**Comment by ParticulaCode** [comment]
Hey, please follow the video from here and make sure you did everything properly:
https://youtu.be/SjlsfxbiFwc
